### ISSUE TITLE
DOING and CRITICAL treeviews not being updated

### ISSUE THREAD

**Issue by tredition** [bmpi-dev/vscode-todo-plus-plus#2]
I have a TODO file for my project like this:

`

Todo:
Heading 1:
 ☐ Task 1 @doing 
 ☐ Task 2 @critical 
 ☐ Task 3
`
For "Task 1" and "Task 2" I do not see any items in the DOING and CRITICAL treeview, not even after saving the TODO file.

**Comment by madawei2699** [comment]
you need add a Tab space before task item

**Comment by tredition** [comment]
I tried but this doesn't work. I'm using Ctrl+Enter to create new task item. When I'm restarting VS Code, the treeview will reload and show the right things but not during work.

**Comment by madawei2699** [comment]
can you show me a capture image of vscode?

tredition <notifications@github.com>于2020年4月27日 周一下午1:43写道：

**Comment by tredition** [comment]
This is the view after saving the TODO file:
![image](https://user-images.githubusercontent.com/50625823/80452639-f88d6500-8926-11ea-8921-f9f3f7a420c1.png)

The Files section is updated properly, but not CRITICAL and DOING.

**Comment by madawei2699** [comment]
You file extension must be *.todo, this image show you file has not a correct .todo extension.
在 2020年4月28日 +0800 PM2:05，tredition <notifications@github.com>，写道：

**Comment by tredition** [comment]
Doesn't change anything. Item 5 should be unter DOING but isn't.
![image](https://user-images.githubusercontent.com/50625823/80564124-38b71b00-89ed-11ea-88f8-c7bb6ab31184.png)

**Comment by madawei2699** [comment]
contact me use telegram：https://t.me/bmpidev , I will help you look deep in this problem.
2020年4月29日 +0800 PM1:44 tredition <notifications@github.com>，写道：

**Comment by alizehctl** [comment]
I have the same problem. In my case it's not even detecting the file:

![image](https://github.com/bmpi-dev/vscode-todo-plus-plus/assets/31581044/eb0c1c54-6b84-425d-b515-bc4365377ebb)
